trigger:
  - main

pool:
  name: Default
  demands:
    - Agent.Name -equals AgentSelfHostedDevops

variables:
  - name: resourceGroupName
    value: 'rg-angular-app'
  - name: aksClusterName
    value: 'aks-cluster'
  - name: location
    value: 'East US'

stages:
- stage: Terraform
  displayName: 'Terraform Deployment using Azure CLI context'
  jobs:
  - job: TerraformJob
    displayName: 'Execute Terraform Commands'
    steps:
    - checkout: self

    - script: |
        echo "Vérification de Terraform installé dans l’agent..."
        terraform --version
      displayName: 'Check Terraform Installation'

    - script: |
        echo "Initialisation et déploiement Terraform avec contexte CLI local..."
        cd terraform
        terraform init
        terraform plan -out=tfplan
        terraform apply -auto-approve tfplan
      displayName: 'Terraform Init, Plan & Apply with local az login'

- stage: DeployToAKS
  displayName: 'Deploy App to AKS'
  dependsOn: Terraform
  jobs:
  - job: Deploy
    displayName: 'Déploiement Angular vers AKS'
    steps:
    - checkout: self

    - script: |
        echo "Utilisation du contexte Azure CLI existant..."
        az account show
        az aks get-credentials --resource-group $(resourceGroupName) --name $(aksClusterName) --overwrite-existing
        echo "Déploiement avec deployment.yaml"
        kubectl apply -f deployment.yaml
      displayName: 'Deploy Angular App to AKS'
