trigger:
  - main

pool:
  name: Default
  demands:
    - Agent.Name -equals AgentSelfHostedDevops

variables:
  - group: TerraformSecrets  # ✅ Récupère automatiquement les secrets depuis la Library
  - name: resourceGroupName
    value: 'rg-angular-app'
  - name: aksClusterName
    value: 'aks-cluster'
  - name: location
    value: 'East US'

stages:
- stage: Terraform
  displayName: 'Terraform Deployment (avec client credentials)'
  jobs:
  - job: TerraformJob
    displayName: 'Execute Terraform Commands'
    steps:
    - checkout: self

    - script: |
        echo "Vérification de Terraform installé dans l’agent..."
        terraform -v
      displayName: 'Check Terraform Installation'

    - script: |
        echo "Initialisation et déploiement Terraform avec client_id, client_secret, tenant_id, subscription_id..."
        cd terraform
        terraform init
        terraform plan \
          -var "client_secret=$(client_secret)" \
          -var "tenant_id=$(tenant_id)" \
          -var "client_id=$(client_id)" \
          -var "subscription_id=$(subscription_id)" \
          -out=tfplan
        terraform apply -auto-approve tfplan
      displayName: 'Terraform Init, Plan & Apply with client credentials'

- stage: DeployToAKS
  displayName: 'Deploy App to AKS'
  dependsOn: Terraform
  jobs:
  - job: Deploy
    displayName: 'Déploiement Angular vers AKS'
    steps:
    - checkout: self

    - script: |
        echo "Authentification à Azure via Azure CLI avec client credentials..."
        az login --service-principal -u $(client_id) -p $(client_secret) --tenant $(tenant_id)
        az aks get-credentials --resource-group $(resourceGroupName) --name $(aksClusterName) --overwrite-existing
        echo "Déploiement des ressources avec deployment.yaml"
        kubectl apply -f deployment.yaml
      displayName: 'Deploy Angular App to AKS'
