trigger:
  - main

pool:
  name: Default
  demands:
    - Agent.Name -equals AgentSelfHostedDevops

variables:
  - group: TerraformSecrets
  - name: resourceGroupName
    value: 'rg-angular-app'
  - name: aksClusterName
    value: 'aks-cluster'
  - name: location
    value: 'East US'

stages:
- stage: Terraform
  displayName: 'Terraform Deployment'
  jobs:
  - job: TerraformJob
    displayName: 'Execute Terraform Commands with Client Credentials'
    steps:
    - checkout: self

    - script: |
        echo "Vérification de Terraform installé dans l’agent..."
        terraform --version
      displayName: 'Check Terraform Installation'

    - script: |
        echo "Initialisation et déploiement Terraform avec credentials..."
        cd terraform
        terraform init
        terraform plan \
          -var "client_secret=$(ARM_CLIENT_SECRET)" \
          -var "tenant_id=$(ARM_TENANT_ID)" \
          -var "client_id=$(ARM_CLIENT_ID)" \
          -var "subscription_id=$(ARM_SUBSCRIPTION_ID)" \
          -out=tfplan
        terraform apply -auto-approve tfplan
      displayName: 'Terraform Init, Plan & Apply (via client credentials)'

- stage: DeployToAKS
  displayName: 'Deploy App to AKS'
  dependsOn: Terraform
  jobs:
  - job: Deploy
    displayName: 'Deploy Angular vers AKS'
    steps:
    - checkout: self

    - script: |
        echo "Authentification Azure via az login (manual)..."
        az login --service-principal -u $(ARM_CLIENT_ID) -p $(ARM_CLIENT_SECRET) --tenant $(ARM_TENANT_ID)
        az aks get-credentials --resource-group $(resourceGroupName) --name $(aksClusterName) --overwrite-existing
        echo "Déploiement avec deployment.yaml"
        kubectl apply -f deployment.yaml
      displayName: 'Deploy Angular App to AKS'
